"use client";

import { useEffect, useRef, useState } from "react";
import { motion, useInView, useScroll, useTransform } from "framer-motion";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Star, Shield, Zap, Flame, Leaf, Coffee, Check, ChevronDown, MessageCircle } from "lucide-react";

// ============================================================
// SLIM30 — Termogênico Premium Landing Page
// Generated by AIOX Web Design Squad
// Agentes: Vex (Design) + Copy + Dev + Motion + Review
// ============================================================

const ACCENT = "#FF6835";
const ACCENT2 = "#FF8F00";

function FadeInSection({ children, delay = 0, className = "" }: { children: React.ReactNode; delay?: number; className?: string }) {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });
  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 32 }}
      animate={isInView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.7, delay, ease: [0.16, 1, 0.3, 1] }}
      className={className}
    >
      {children}
    </motion.div>
  );
}

function Counter({ target, suffix = "" }: { target: number; suffix?: string }) {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true });
  const [count, setCount] = useState(0);

  useEffect(() => {
    if (!isInView) return;
    const duration = 1800;
    const start = Date.now();
    const tick = () => {
      const elapsed = Date.now() - start;
      const progress = Math.min(elapsed / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      setCount(Math.floor(eased * target));
      if (progress < 1) requestAnimationFrame(tick);
      else setCount(target);
    };
    requestAnimationFrame(tick);
  }, [isInView, target]);

  return <span ref={ref}>{count.toLocaleString("pt-BR")}{suffix}</span>;
}

const faqs = [
  {
    q: "SLIM30 tem efeitos colaterais?",
    a: "SLIM30 é formulado com ingredientes naturais bioativos em doses seguras. A maioria das clientes não relata efeitos adversos. Em casos de sensibilidade à cafeína, recomendamos tomar pela manhã com alimento."
  },
  {
    q: "Em quanto tempo vejo resultados?",
    a: "A maioria das clientes relata sentir mais disposição e energia nos primeiros 7 dias. Os resultados visuais aparecem a partir da 2ª semana, com a média de -8kg sendo atingida ao fim dos 30 dias."
  },
  {
    q: "Posso tomar junto com outros suplementos?",
    a: "Sim, SLIM30 é compatível com vitaminas, proteínas e creatina. Evite combinar com outros estimulantes ou termogênicos."
  },
  {
    q: "E se não funcionar para mim?",
    a: "Você tem 30 dias de garantia incondicional. Se por qualquer motivo não ficar satisfeita, basta entrar em contato e devolvemos 100% do seu dinheiro. Sem perguntas."
  },
  {
    q: "Como funciona o envio?",
    a: "Enviamos para todo o Brasil via Correios e transportadoras. O prazo médio é de 3 a 7 dias úteis. Frete grátis em todos os pedidos."
  }
];

const ingredients = [
  { icon: Flame, name: "Capsaicina", dose: "150mg", benefit: "Eleva temperatura corporal, queima até +15% de calorias em repouso" },
  { icon: Leaf, name: "EGCG (Chá Verde)", dose: "400mg", benefit: "Potente antioxidante que oxida tecido adiposo, especialmente gordura abdominal" },
  { icon: Coffee, name: "Cafeína Anidra", dose: "200mg", benefit: "Energia limpa e duradoura sem o crash — foco total por 6-8 horas" },
  { icon: Zap, name: "Gengibre Bioativo", dose: "250mg", benefit: "Antiinflamatório natural que melhora digestão e potencializa os outros ingredientes" },
  { icon: Star, name: "Piperina", dose: "10mg", benefit: "Aumenta em até 2000% a biodisponibilidade dos demais compostos" },
];

const testimonials = [
  {
    name: "Fernanda S.",
    city: "São Paulo, SP",
    stars: 5,
    before: "72kg",
    after: "63kg",
    text: "Perdi 9kg em 35 dias sem academia. Nunca acreditei que um suplemento pudesse fazer tanta diferença. O que me surpreendeu mais foi a energia — eu trabalho 10h por dia e ainda tinha disposição pra sair à noite.",
    initials: "FS",
    color: "#FF6835"
  },
  {
    name: "Camila R.",
    city: "Belo Horizonte, MG",
    stars: 5,
    before: "68kg",
    after: "60kg",
    text: "Tentei tudo nos últimos 3 anos. Dieta low carb, jejum, academia. Nada funcionou. Com o SLIM30 perdi 8kg em 30 dias e o mais importante: não voltei a engordar. A compulsão por doce desapareceu.",
    initials: "CR",
    color: "#FF8F00"
  },
  {
    name: "Juliana M.",
    city: "Rio de Janeiro, RJ",
    stars: 5,
    before: "85kg",
    after: "74kg",
    text: "Depois da segunda gravidez meu metabolismo simplesmente parou. SLIM30 foi a virada. 11kg em 45 dias. Meu médico ficou impressionado com os exames — colesterol, triglicérides, tudo melhorou junto.",
    initials: "JM",
    color: "#E879F9"
  },
];

const plans = [
  {
    name: "Starter",
    qty: "1 frasco",
    days: "30 dias",
    price: 197,
    installment: "3x R$65,67",
    perDay: "R$6,57/dia",
    featured: false,
    saving: null
  },
  {
    name: "Transformação",
    qty: "2 frascos",
    days: "60 dias",
    price: 297,
    installment: "3x R$99,00",
    perDay: "R$4,95/dia",
    featured: true,
    saving: "Economize R$97"
  },
  {
    name: "Resultado Total",
    qty: "3 frascos",
    days: "90 dias",
    price: 397,
    installment: "3x R$132,33",
    perDay: "R$4,41/dia",
    featured: false,
    saving: "Economize R$194"
  },
];

export default function Slim30Page() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const { scrollY } = useScroll();
  const heroY = useTransform(scrollY, [0, 600], [0, -120]);
  const heroOpacity = useTransform(scrollY, [0, 400], [1, 0.3]);

  return (
    <div style={{ background: "#0A080B", color: "#F5F0F8", fontFamily: "'Inter', 'DM Sans', system-ui, sans-serif", minHeight: "100vh", overflowX: "hidden" }}>

      {/* Back to studio */}
      <div className="fixed top-4 left-4 z-50">
        <Link href="/briefs" className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium transition-all"
          style={{ background: "rgba(0,0,0,0.7)", border: "1px solid rgba(255,104,53,0.2)", color: "rgba(245,240,248,0.5)", backdropFilter: "blur(8px)" }}
          onMouseEnter={e => {
            (e.currentTarget as HTMLElement).style.color = ACCENT;
            (e.currentTarget as HTMLElement).style.borderColor = ACCENT;
          }}
          onMouseLeave={e => {
            (e.currentTarget as HTMLElement).style.color = "rgba(245,240,248,0.5)";
            (e.currentTarget as HTMLElement).style.borderColor = "rgba(255,104,53,0.2)";
          }}
        >
          <ArrowLeft size={12} /> AIOX Studio
        </Link>
      </div>

      {/* ──────────── HERO ──────────── */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
        {/* BG glow */}
        <div className="absolute inset-0 pointer-events-none">
          <div style={{ position: "absolute", top: "20%", left: "50%", transform: "translateX(-50%)", width: 600, height: 600, background: `radial-gradient(circle, ${ACCENT}18 0%, transparent 70%)`, filter: "blur(40px)" }} />
          <div style={{ position: "absolute", bottom: "10%", right: "10%", width: 300, height: 300, background: `radial-gradient(circle, ${ACCENT2}10 0%, transparent 70%)`, filter: "blur(60px)" }} />
        </div>

        {/* Grid pattern */}
        <div className="absolute inset-0 opacity-[0.03]" style={{ backgroundImage: "linear-gradient(rgba(255,104,53,0.3) 1px, transparent 1px), linear-gradient(90deg, rgba(255,104,53,0.3) 1px, transparent 1px)", backgroundSize: "60px 60px" }} />

        <motion.div style={{ y: heroY, opacity: heroOpacity }} className="relative z-10 max-w-4xl mx-auto px-6 text-center pt-24 pb-16">
          {/* Badge */}
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5 }}
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold mb-8"
            style={{ background: `${ACCENT}15`, border: `1px solid ${ACCENT}30`, color: ACCENT }}
          >
            <span className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ background: ACCENT }} />
            #1 Termogênico Feminino do Brasil · 50.000+ Transformações
          </motion.div>

          {/* Headline */}
          <motion.h1
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
            className="font-bold leading-tight mb-6"
            style={{ fontSize: "clamp(2.2rem, 6vw, 4.5rem)", letterSpacing: "-0.03em", lineHeight: 1.05 }}
          >
            Você não está falhando.{" "}
            <span style={{ background: `linear-gradient(135deg, ${ACCENT}, ${ACCENT2})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
              Seu metabolismo está
            </span>{" "}
            sabotando você.
          </motion.h1>

          {/* Subheadline */}
          <motion.p
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.25, ease: [0.16, 1, 0.3, 1] }}
            className="text-lg leading-relaxed mb-10 max-w-2xl mx-auto"
            style={{ color: "rgba(245,240,248,0.65)" }}
          >
            SLIM30 reativa seu metabolismo e queima gordura <strong style={{ color: "#F5F0F8" }}>24 horas por dia</strong> — mesmo enquanto você dorme. Com 5 ingredientes bioativos em concentração premium.
          </motion.p>

          {/* CTA */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <button
              className="group flex items-center gap-3 px-8 py-4 rounded-full font-bold text-base transition-all duration-300"
              style={{ background: `linear-gradient(135deg, ${ACCENT}, ${ACCENT2})`, color: "#fff", boxShadow: `0 0 40px ${ACCENT}40, 0 4px 20px rgba(0,0,0,0.4)` }}
              onMouseEnter={e => {
                (e.currentTarget as HTMLElement).style.transform = "scale(1.04)";
                (e.currentTarget as HTMLElement).style.boxShadow = `0 0 60px ${ACCENT}60, 0 8px 30px rgba(0,0,0,0.5)`;
              }}
              onMouseLeave={e => {
                (e.currentTarget as HTMLElement).style.transform = "scale(1)";
                (e.currentTarget as HTMLElement).style.boxShadow = `0 0 40px ${ACCENT}40, 0 4px 20px rgba(0,0,0,0.4)`;
              }}
            >
              Quero Ativar Meu Metabolismo
              <ArrowRight size={18} className="transition-transform group-hover:translate-x-1" />
            </button>
            <p className="text-xs" style={{ color: "rgba(245,240,248,0.4)" }}>
              ✓ 30 dias de garantia &nbsp; ✓ Frete grátis &nbsp; ✓ Entrega em 3-7 dias
            </p>
          </motion.div>

          {/* Stars micro proof */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.6 }}
            className="flex items-center justify-center gap-2 mt-8"
          >
            <div className="flex gap-0.5">
              {[...Array(5)].map((_, i) => (
                <Star key={i} size={14} fill={ACCENT} color={ACCENT} />
              ))}
            </div>
            <span className="text-sm" style={{ color: "rgba(245,240,248,0.5)" }}>
              <strong style={{ color: "#F5F0F8" }}>4.8/5</strong> · 3.200+ avaliações verificadas
            </span>
          </motion.div>

          {/* Product visual */}
          <motion.div
            initial={{ opacity: 0, scale: 0.85 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 1.2, delay: 0.3, ease: [0.16, 1, 0.3, 1] }}
            className="mt-16 mx-auto"
            style={{ maxWidth: 280 }}
          >
            <div className="relative mx-auto rounded-3xl flex items-center justify-center"
              style={{ width: 200, height: 280, margin: "0 auto", background: `linear-gradient(160deg, #1A1218 0%, #110D0F 100%)`, border: `1px solid ${ACCENT}25`, boxShadow: `0 0 80px ${ACCENT}30, 0 0 40px ${ACCENT}15, inset 0 1px 0 rgba(255,255,255,0.06)` }}>
              <div style={{ textAlign: "center" }}>
                <div style={{ fontSize: 48, marginBottom: 8 }}>🔥</div>
                <div style={{ fontSize: 28, fontWeight: 900, letterSpacing: "-0.04em", background: `linear-gradient(135deg, ${ACCENT}, ${ACCENT2})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>SLIM30</div>
                <div style={{ fontSize: 11, color: "rgba(245,240,248,0.4)", letterSpacing: "0.15em", textTransform: "uppercase", marginTop: 4 }}>Termogênico Premium</div>
                <div style={{ fontSize: 10, color: "rgba(245,240,248,0.25)", marginTop: 16 }}>60 cápsulas · 30 doses</div>
              </div>
              {/* Glow ring */}
              <div className="absolute inset-0 rounded-3xl" style={{ background: `radial-gradient(circle at 50% 0%, ${ACCENT}12 0%, transparent 60%)` }} />
            </div>
          </motion.div>
        </motion.div>

        {/* Scroll indicator */}
        <motion.div
          animate={{ y: [0, 8, 0] }}
          transition={{ repeat: Infinity, duration: 2 }}
          className="absolute bottom-8 left-1/2 -translate-x-1/2"
        >
          <ChevronDown size={20} style={{ color: "rgba(245,240,248,0.2)" }} />
        </motion.div>
      </section>

      {/* ──────────── NUMBERS ──────────── */}
      <section className="py-16 relative" style={{ borderTop: "1px solid rgba(255,104,53,0.1)", borderBottom: "1px solid rgba(255,104,53,0.1)", background: "rgba(255,104,53,0.02)" }}>
        <div className="max-w-5xl mx-auto px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {[
              { value: 50000, suffix: "+", label: "Clientes Satisfeitas" },
              { value: 8, suffix: "kg", label: "Média de Perda em 30 dias" },
              { value: 3200, suffix: "+", label: "Avaliações 5 Estrelas" },
              { value: 98, suffix: "%", label: "Recomendam para Amigas" },
            ].map(({ value, suffix, label }) => (
              <FadeInSection key={label} className="text-center">
                <div className="text-4xl font-black mb-1" style={{ background: `linear-gradient(135deg, ${ACCENT}, ${ACCENT2})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
                  <Counter target={value} suffix={suffix} />
                </div>
                <div className="text-sm" style={{ color: "rgba(245,240,248,0.45)" }}>{label}</div>
              </FadeInSection>
            ))}
          </div>
        </div>
      </section>

      {/* ──────────── DOR ──────────── */}
      <section className="py-24 max-w-3xl mx-auto px-6">
        <FadeInSection>
          <p className="text-xs font-bold uppercase tracking-[0.2em] mb-4" style={{ color: ACCENT }}>Soa familiar?</p>
          <h2 className="text-3xl md:text-4xl font-bold mb-12" style={{ letterSpacing: "-0.02em" }}>
            Você já tentou de tudo...
          </h2>
        </FadeInSection>

        <div className="space-y-4 mb-12">
          {[
            "Dieta low carb por 3 meses: perdeu 3kg, ganhou 6kg de volta",
            "Academia todo dia: exausta, sem resultado visível",
            "Termogênico barato: coração acelerado, ansiedade, zero diferença na balança",
            "Jejum intermitente: irritação, fome insuportável, metabolismo ainda mais lento",
            "Água, salada, sacrifício: tudo certo no papel, nada funcionando na prática",
          ].map((item, i) => (
            <FadeInSection key={i} delay={i * 0.08}>
              <div className="flex items-start gap-4 p-4 rounded-xl" style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.05)" }}>
                <span className="text-xl shrink-0 mt-0.5">❌</span>
                <p style={{ color: "rgba(245,240,248,0.6)" }}>{item}</p>
              </div>
            </FadeInSection>
          ))}
        </div>

        <FadeInSection>
          <div className="p-8 rounded-2xl text-center" style={{ background: `${ACCENT}08`, border: `1px solid ${ACCENT}20` }}>
            <div className="text-4xl mb-4">💡</div>
            <h3 className="text-xl font-bold mb-3">O problema não é você. É o seu metabolismo.</h3>
            <p style={{ color: "rgba(245,240,248,0.55)", lineHeight: 1.7 }}>
              Depois dos 28 anos, o metabolismo desacelera naturalmente. Cada dieta restritiva torna isso pior. Sem a reativação correta, nenhuma dieta ou exercício vai funcionar como deveria.
            </p>
          </div>
        </FadeInSection>
      </section>

      {/* ──────────── MECANISMO ──────────── */}
      <section className="py-24 relative overflow-hidden" style={{ background: "rgba(255,104,53,0.025)" }}>
        <div className="absolute inset-0" style={{ backgroundImage: `radial-gradient(${ACCENT}08 1px, transparent 1px)`, backgroundSize: "30px 30px" }} />
        <div className="max-w-5xl mx-auto px-6 relative z-10">
          <FadeInSection className="text-center mb-16">
            <p className="text-xs font-bold uppercase tracking-[0.2em] mb-4" style={{ color: ACCENT }}>O diferencial SLIM30</p>
            <h2 className="text-3xl md:text-4xl font-bold" style={{ letterSpacing: "-0.02em" }}>
              Como funciona diferente<br />de tudo que você já tentou
            </h2>
          </FadeInSection>

          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                icon: "🔥",
                title: "Termogênese Ativada",
                desc: "Eleva sua temperatura corporal interna, forçando o corpo a queimar mais calorias mesmo em repouso. Funciona 24 horas."
              },
              {
                icon: "🧠",
                title: "Supressão de Fome",
                desc: "Reduz a compulsão alimentar sem superestimular o sistema nervoso. Você come menos sem sofrimento."
              },
              {
                icon: "⚡",
                title: "Energia Sustentada",
                desc: "Disposição total o dia inteiro, sem o crash de cafeína. Trabalha, treina e ainda tem energia para o que importa."
              },
            ].map((item, i) => (
              <FadeInSection key={i} delay={i * 0.1}>
                <div className="p-6 rounded-2xl h-full" style={{ background: "#100E12", border: `1px solid ${ACCENT}15`, boxShadow: `0 0 30px ${ACCENT}08` }}>
                  <div className="text-4xl mb-4">{item.icon}</div>
                  <h3 className="font-bold text-lg mb-3">{item.title}</h3>
                  <p style={{ color: "rgba(245,240,248,0.5)", lineHeight: 1.7, fontSize: 14 }}>{item.desc}</p>
                </div>
              </FadeInSection>
            ))}
          </div>
        </div>
      </section>

      {/* ──────────── INGREDIENTES ──────────── */}
      <section className="py-24 max-w-4xl mx-auto px-6">
        <FadeInSection className="text-center mb-16">
          <p className="text-xs font-bold uppercase tracking-[0.2em] mb-4" style={{ color: ACCENT }}>Fórmula científica</p>
          <h2 className="text-3xl md:text-4xl font-bold mb-4" style={{ letterSpacing: "-0.02em" }}>
            5 ingredientes premium.<br />1 resultado comprovado.
          </h2>
          <p style={{ color: "rgba(245,240,248,0.45)", maxWidth: 500, margin: "0 auto" }}>
            Cada ingrediente foi selecionado por eficácia comprovada em estudos clínicos e combinado para potencializar o efeito dos demais.
          </p>
        </FadeInSection>

        <div className="space-y-4">
          {ingredients.map((item, i) => {
            const Icon = item.icon;
            return (
              <FadeInSection key={i} delay={i * 0.07}>
                <div className="flex items-center gap-5 p-5 rounded-xl transition-all duration-300"
                  style={{ background: "rgba(255,255,255,0.025)", border: "1px solid rgba(255,255,255,0.06)" }}
                  onMouseEnter={e => {
                    (e.currentTarget as HTMLElement).style.borderColor = `${ACCENT}25`;
                    (e.currentTarget as HTMLElement).style.background = `${ACCENT}05`;
                  }}
                  onMouseLeave={e => {
                    (e.currentTarget as HTMLElement).style.borderColor = "rgba(255,255,255,0.06)";
                    (e.currentTarget as HTMLElement).style.background = "rgba(255,255,255,0.025)";
                  }}
                >
                  <div className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0" style={{ background: `${ACCENT}12`, border: `1px solid ${ACCENT}20` }}>
                    <Icon size={18} style={{ color: ACCENT }} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 mb-1 flex-wrap">
                      <span className="font-semibold">{item.name}</span>
                      <span className="text-xs px-2 py-0.5 rounded-full font-mono" style={{ background: `${ACCENT}10`, color: ACCENT }}>{item.dose}</span>
                    </div>
                    <p className="text-sm" style={{ color: "rgba(245,240,248,0.45)" }}>{item.benefit}</p>
                  </div>
                </div>
              </FadeInSection>
            );
          })}
        </div>
      </section>

      {/* ──────────── DEPOIMENTOS ──────────── */}
      <section className="py-24 relative overflow-hidden" style={{ background: "rgba(0,0,0,0.3)" }}>
        <div className="max-w-5xl mx-auto px-6">
          <FadeInSection className="text-center mb-16">
            <p className="text-xs font-bold uppercase tracking-[0.2em] mb-4" style={{ color: ACCENT }}>Resultados reais</p>
            <h2 className="text-3xl md:text-4xl font-bold" style={{ letterSpacing: "-0.02em" }}>
              Histórias que inspiram
            </h2>
          </FadeInSection>

          <div className="grid md:grid-cols-3 gap-6">
            {testimonials.map((t, i) => (
              <FadeInSection key={i} delay={i * 0.1}>
                <div className="p-6 rounded-2xl h-full flex flex-col" style={{ background: "#100E12", border: "1px solid rgba(255,255,255,0.06)" }}>
                  {/* Stars */}
                  <div className="flex gap-0.5 mb-4">
                    {[...Array(t.stars)].map((_, s) => (
                      <Star key={s} size={12} fill={ACCENT} color={ACCENT} />
                    ))}
                  </div>

                  {/* Before/after */}
                  <div className="flex items-center gap-3 mb-4 p-3 rounded-xl" style={{ background: "rgba(255,255,255,0.03)" }}>
                    <div className="text-center">
                      <div className="text-xs mb-0.5" style={{ color: "rgba(245,240,248,0.35)" }}>antes</div>
                      <div className="text-lg font-bold" style={{ color: "rgba(245,240,248,0.5)" }}>{t.before}</div>
                    </div>
                    <div className="flex-1 flex items-center justify-center">
                      <ArrowRight size={16} style={{ color: ACCENT }} />
                    </div>
                    <div className="text-center">
                      <div className="text-xs mb-0.5" style={{ color: "rgba(245,240,248,0.35)" }}>depois</div>
                      <div className="text-lg font-bold" style={{ color: ACCENT }}>{t.after}</div>
                    </div>
                  </div>

                  <p className="text-sm leading-relaxed flex-1 mb-5" style={{ color: "rgba(245,240,248,0.6)" }}>
                    &ldquo;{t.text}&rdquo;
                  </p>

                  <div className="flex items-center gap-3">
                    <div className="w-9 h-9 rounded-full flex items-center justify-center text-sm font-bold shrink-0" style={{ background: t.color + "20", color: t.color }}>
                      {t.initials}
                    </div>
                    <div>
                      <div className="text-sm font-semibold">{t.name}</div>
                      <div className="text-xs" style={{ color: "rgba(245,240,248,0.35)" }}>{t.city}</div>
                    </div>
                  </div>
                </div>
              </FadeInSection>
            ))}
          </div>
        </div>
      </section>

      {/* ──────────── OFERTA ──────────── */}
      <section className="py-24 max-w-5xl mx-auto px-6" id="comprar">
        <FadeInSection className="text-center mb-4">
          <p className="text-xs font-bold uppercase tracking-[0.2em] mb-4" style={{ color: ACCENT }}>Escolha seu plano</p>
          <h2 className="text-3xl md:text-4xl font-bold mb-4" style={{ letterSpacing: "-0.02em" }}>
            Quanto vale 30 dias de transformação?
          </h2>
          <p style={{ color: "rgba(245,240,248,0.45)" }}>
            Garantia de 30 dias. Frete grátis. Resultados ou seu dinheiro de volta.
          </p>
        </FadeInSection>

        <div className="grid md:grid-cols-3 gap-6 mt-12">
          {plans.map((plan, i) => (
            <FadeInSection key={i} delay={i * 0.1}>
              <div className="p-6 rounded-2xl flex flex-col relative overflow-hidden transition-all duration-300"
                style={{
                  background: plan.featured ? `linear-gradient(160deg, ${ACCENT}15 0%, transparent 60%), #100E12` : "#100E12",
                  border: plan.featured ? `1px solid ${ACCENT}40` : "1px solid rgba(255,255,255,0.07)",
                  boxShadow: plan.featured ? `0 0 40px ${ACCENT}15` : "none",
                  transform: plan.featured ? "scale(1.03)" : "scale(1)"
                }}
              >
                {plan.featured && (
                  <div className="absolute top-0 left-0 right-0 py-1.5 text-center text-xs font-bold" style={{ background: `linear-gradient(90deg, ${ACCENT}, ${ACCENT2})`, color: "#fff" }}>
                    ⭐ MAIS VENDIDO
                  </div>
                )}
                <div className={plan.featured ? "mt-8" : ""}>
                  <p className="text-sm font-semibold mb-1" style={{ color: "rgba(245,240,248,0.5)" }}>{plan.name}</p>
                  <p className="text-lg font-bold mb-4">{plan.qty} · {plan.days}</p>

                  {plan.saving && (
                    <div className="inline-block px-2 py-0.5 rounded text-xs font-bold mb-3" style={{ background: `${ACCENT}20`, color: ACCENT }}>
                      {plan.saving}
                    </div>
                  )}

                  <div className="mb-1">
                    <span className="text-4xl font-black">R${plan.price}</span>
                  </div>
                  <p className="text-xs mb-1" style={{ color: "rgba(245,240,248,0.4)" }}>ou {plan.installment}</p>
                  <p className="text-xs mb-6" style={{ color: "rgba(245,240,248,0.3)" }}>{plan.perDay}</p>

                  <button
                    className="w-full py-3 rounded-xl font-bold text-sm transition-all duration-200"
                    style={plan.featured ? {
                      background: `linear-gradient(135deg, ${ACCENT}, ${ACCENT2})`,
                      color: "#fff",
                      boxShadow: `0 4px 20px ${ACCENT}30`
                    } : {
                      background: "rgba(255,255,255,0.06)",
                      color: "#F5F0F8",
                      border: "1px solid rgba(255,255,255,0.1)"
                    }}
                    onMouseEnter={e => {
                      if (!plan.featured) {
                        (e.currentTarget as HTMLElement).style.background = `${ACCENT}15`;
                        (e.currentTarget as HTMLElement).style.borderColor = ACCENT;
                      }
                    }}
                    onMouseLeave={e => {
                      if (!plan.featured) {
                        (e.currentTarget as HTMLElement).style.background = "rgba(255,255,255,0.06)";
                        (e.currentTarget as HTMLElement).style.borderColor = "rgba(255,255,255,0.1)";
                      }
                    }}
                  >
                    Comprar Agora →
                  </button>
                </div>
              </div>
            </FadeInSection>
          ))}
        </div>

        {/* Garantias */}
        <FadeInSection delay={0.3}>
          <div className="mt-10 flex flex-wrap justify-center gap-6 pt-8" style={{ borderTop: "1px solid rgba(255,255,255,0.06)" }}>
            {[
              { icon: Shield, text: "30 dias de garantia total" },
              { icon: Check, text: "Frete grátis para todo o Brasil" },
              { icon: Zap, text: "Entrega expressa 3-7 dias úteis" },
              { icon: Star, text: "4.8/5 ★ em 3.200+ avaliações" },
            ].map(({ icon: Icon, text }) => (
              <div key={text} className="flex items-center gap-2 text-sm" style={{ color: "rgba(245,240,248,0.45)" }}>
                <Icon size={14} style={{ color: ACCENT }} />
                {text}
              </div>
            ))}
          </div>
        </FadeInSection>
      </section>

      {/* ──────────── FAQ ──────────── */}
      <section className="py-24 max-w-2xl mx-auto px-6">
        <FadeInSection className="text-center mb-12">
          <p className="text-xs font-bold uppercase tracking-[0.2em] mb-4" style={{ color: ACCENT }}>Dúvidas?</p>
          <h2 className="text-3xl md:text-4xl font-bold" style={{ letterSpacing: "-0.02em" }}>Perguntas frequentes</h2>
        </FadeInSection>

        <div className="space-y-3">
          {faqs.map((faq, i) => (
            <FadeInSection key={i} delay={i * 0.05}>
              <div className="rounded-xl overflow-hidden" style={{ border: "1px solid rgba(255,255,255,0.07)" }}>
                <button
                  className="w-full flex items-center justify-between p-5 text-left"
                  style={{ background: openFaq === i ? `${ACCENT}08` : "rgba(255,255,255,0.02)" }}
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                >
                  <span className="font-medium pr-4">{faq.q}</span>
                  <motion.div animate={{ rotate: openFaq === i ? 180 : 0 }} transition={{ duration: 0.25 }}>
                    <ChevronDown size={16} style={{ color: ACCENT }} />
                  </motion.div>
                </button>
                <motion.div
                  initial={false}
                  animate={{ height: openFaq === i ? "auto" : 0 }}
                  style={{ overflow: "hidden" }}
                  transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
                >
                  <p className="px-5 pb-5 text-sm leading-relaxed" style={{ color: "rgba(245,240,248,0.55)" }}>
                    {faq.a}
                  </p>
                </motion.div>
              </div>
            </FadeInSection>
          ))}
        </div>
      </section>

      {/* ──────────── CTA FINAL ──────────── */}
      <section className="py-24 relative overflow-hidden">
        <div className="absolute inset-0" style={{ background: `radial-gradient(ellipse at center, ${ACCENT}12 0%, transparent 70%)` }} />
        <div className="max-w-2xl mx-auto px-6 text-center relative z-10">
          <FadeInSection>
            <div className="text-6xl mb-6">🔥</div>
            <h2 className="text-3xl md:text-5xl font-black mb-6 leading-tight" style={{ letterSpacing: "-0.03em" }}>
              Seu metabolismo pode mudar.<br />
              <span style={{ background: `linear-gradient(135deg, ${ACCENT}, ${ACCENT2})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
                Começa agora.
              </span>
            </h2>
            <p className="mb-10 text-lg" style={{ color: "rgba(245,240,248,0.55)" }}>
              Junte-se a 50.000 mulheres que já transformaram o corpo e a autoestima com SLIM30. Você tem 30 dias para experimentar — sem risco.
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <button
                className="flex items-center gap-3 px-8 py-4 rounded-full font-bold text-base transition-all duration-300"
                style={{ background: `linear-gradient(135deg, ${ACCENT}, ${ACCENT2})`, color: "#fff", boxShadow: `0 0 60px ${ACCENT}40` }}
                onMouseEnter={e => (e.currentTarget as HTMLElement).style.transform = "scale(1.04)"}
                onMouseLeave={e => (e.currentTarget as HTMLElement).style.transform = "scale(1)"}
              >
                Quero SLIM30 com Garantia
                <ArrowRight size={18} />
              </button>
              <button
                className="flex items-center gap-2 px-6 py-4 rounded-full font-medium text-sm transition-all duration-200"
                style={{ background: "#25D366" + "15", color: "#25D366", border: "1px solid #25D36625" }}
                onMouseEnter={e => (e.currentTarget as HTMLElement).style.background = "#25D36625"}
                onMouseLeave={e => (e.currentTarget as HTMLElement).style.background = "#25D36615"}
              >
                <MessageCircle size={16} /> Falar no WhatsApp
              </button>
            </div>
            <p className="mt-6 text-xs" style={{ color: "rgba(245,240,248,0.3)" }}>
              🔒 Compra 100% segura · SSL · 30 dias de garantia incondicional
            </p>
          </FadeInSection>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="py-8 text-center" style={{ borderTop: "1px solid rgba(255,255,255,0.05)" }}>
        <p className="text-xs mb-2" style={{ color: "rgba(245,240,248,0.2)" }}>
          SLIM30 Suplementos LTDA · CNPJ 00.000.000/0001-00 · contato@slim30.com.br
        </p>
        <p className="text-xs" style={{ color: "rgba(245,240,248,0.15)" }}>
          *Os resultados podem variar de pessoa para pessoa. Consulte um médico antes de usar qualquer suplemento.
        </p>
        <p className="text-xs mt-4" style={{ color: "rgba(245,240,248,0.12)" }}>
          Landing page gerada pelo{" "}
          <Link href="/" style={{ color: "#00E676" }}>AIOX Web Design Squad</Link>
        </p>
      </footer>

      <style jsx global>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap');
        * { box-sizing: border-box; }
        html { scroll-behavior: smooth; }
      `}</style>
    </div>
  );
}
